### ISSUE TITLE
Use "serde-yaml" to cleanup configuration loader ?

### ISSUE THREAD

**Issue by dlecan** [sqli-nantes/dockup#2]
[Serde-yaml](https://github.com/dtolnay/serde-yaml) allows "PORO" serialization/deserialisation into yaml files.
It could cleanup configuration file loader ([yaml_to_model](https://github.com/sqli-nantes/dockup/blob/master/dockup_utils/src/config/load.rs#L43) in 2 LOC).

**Comment by rguillome** [comment]
Changes made in the last update.
Simplify the modules structure too (usage of syntex/serde_codegen and compiling features)

**Comment by rguillome** [comment]
Changes made in the last update.
Simplify the modules structure too (usage of syntex/serde_codegen and compiling features)
